// Sugerencias para el campo "Ciudad" (no es una lista cerrada: se puede escribir cualquiera).
// Capitales de departamento y municipios de las principales áreas metropolitanas.
export const COLOMBIA_CITIES = [
  // Capitales
  "Bogotá",
  "Medellín",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Cúcuta",
  "Bucaramanga",
  "Pereira",
  "Santa Marta",
  "Ibagué",
  "Villavicencio",
  "Pasto",
  "Manizales",
  "Montería",
  "Neiva",
  "Armenia",
  "Valledupar",
  "Sincelejo",
  "Popayán",
  "Tunja",
  "Riohacha",
  "Florencia",
  "Yopal",
  "Quibdó",
  "Arauca",
  "San Andrés",
  "Mocoa",
  "Leticia",
  "Inírida",
  "San José del Guaviare",
  "Mitú",
  "Puerto Carreño",
  // Sabana de Bogotá y Cundinamarca
  "Soacha",
  "Chía",
  "Cajicá",
  "Zipaquirá",
  "Cota",
  "Funza",
  "Mosquera",
  "Madrid",
  "Facatativá",
  "La Calera",
  "Sopó",
  "Tocancipá",
  "Tenjo",
  "Tabio",
  "Fusagasugá",
  "Girardot",
  // Valle de Aburrá y oriente antioqueño
  "Bello",
  "Itagüí",
  "Envigado",
  "Sabaneta",
  "La Estrella",
  "Copacabana",
  "Girardota",
  "Rionegro",
  "La Ceja",
  "Marinilla",
  "Guarne",
  "El Retiro",
  "Apartadó",
  // Valle del Cauca
  "Palmira",
  "Jamundí",
  "Yumbo",
  "Tuluá",
  "Buga",
  "Cartago",
  "Buenaventura",
  // Caribe
  "Soledad",
  "Malambo",
  "Puerto Colombia",
  "Turbaco",
  "Magangué",
  "Ciénaga",
  "Maicao",
  "Lorica",
  "Sahagún",
  "Aguachica",
  // Santanderes
  "Floridablanca",
  "Girón",
  "Piedecuesta",
  "Barrancabermeja",
  "Villa del Rosario",
  "Los Patios",
  "Ocaña",
  // Eje cafetero, Boyacá, Tolima, Huila, Nariño
  "Dosquebradas",
  "Santa Rosa de Cabal",
  "Calarcá",
  "Chinchiná",
  "La Dorada",
  "Duitama",
  "Sogamoso",
  "Chiquinquirá",
  "Espinal",
  "Pitalito",
  "Garzón",
  "Ipiales",
  "Tumaco",
] as const;
